### ISSUE TITLE
cyvcf2/cyvcf2.pyx:1466:32: Cannot assign type 'double' to 'int'

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/mutacc#92]
While working on another PR I've realised that I can't install this repo. Tested locally by following instructions on the readme and using a conda env with python=3.8

More info:

```
Cyvcf2/cyvcf2.pyx:1481:32: Cannot assign type 'double' to 'int'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-install-0_4nu148/cyvcf2_fc26c7a774b14adb95c5f69547e3a19b/setup.py", line 73, in <module>
          setup(
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/Users/chiararasi/miniconda3/envs/mutacc/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: cyvcf2/cyvcf2.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cyvcf2
  Running setup.py clean for cyvcf2
Failed to build cyvcf2
ERROR: Could not build wheels for cyvcf2, which is required to install pyproject.toml-based projects
(mutacc) chiararasi@n187-p80 mutacc %
```

**Comment by northwestwitch** [comment]
The installation was actually working when python 3.6 was still supported
